export const images = {
  yourlogo: "/assets/yourlogo.svg",
  brainwave: "/assets/brainwave.svg",
  check: "/assets/check.svg",
  socialMediaIcon: "/assets/Social_media_icon.png",
  check2: "/assets/check-02.svg",
  loading1: "/assets/loading-01.svg",
  seo: "/assets/seo.png",
  brainwaveSymbol: "/assets/brainwave-symbol.svg",
  brainwaveWhiteSymbol: "/assets/brainwave-symbol-white.svg",
  play: "/assets/play.svg",
  googleAds: "/assets/google-ads.png",
  gradient: "/assets/gradient.png",
  smallSphere: "/assets/4-small.png",
  grid: "/assets/grid.png",
  homeSmile: "/assets/home-smile.svg",
  file02: "/assets/file-02.svg",
  searchMd: "/assets/search-md.svg",
  plusSquare: "/assets/plus-square.svg",
  recording03: "/assets/recording-03.svg",
  recording01: "/assets/recording-01.svg",
  disc02: "/assets/disc-02.svg",
  chromecast: "/assets/chrome-cast.svg",
  sliders04: "/assets/sliders-04.svg",
  loading: "/assets/loading.png",
  background: "/assets/background.jpg",
  curve: "/assets/hero/curve.png",
  robot: "/assets/hero/robot.jpg",
  heroVideo: "/assets/hero/Agency.mp4",
  heroBackground: "/assets/hero/hero-background.jpg",
  curve1: "/assets/collaboration/curve-1.svg",
  curve2: "/assets/collaboration/curve-2.svg",
  discord: "/assets/collaboration/discord.png",
  figma: "/assets/collaboration/figma.png",
  framer: "/assets/collaboration/framer.png",
  notion: "/assets/collaboration/notion.png",
  photoshop: "/assets/collaboration/photoshop.png",
  protopie: "/assets/collaboration/protopie.png",
  raindrop: "/assets/collaboration/raindrop.png",
  slack: "/assets/collaboration/slack.png",
  service1: "/assets/services/service-1.png",
  service2: "/assets/services/service-2.png",
  service3: "/assets/services/service-3.png",
  lines: "/assets/pricing/lines.svg",
  stars: "/assets/pricing/stars.svg",
  coins: "/assets/roadmap/coins.png",
  done: "/assets/roadmap/done.svg",
  hero: "/assets/roadmap/hero.png",
  roadmap1: "/assets/roadmap/image-1.png",
  roadmap2: "/assets/roadmap/image-2.png",
  roadmap3: "/assets/roadmap/image-3.png",
  roadmap4: "/assets/roadmap/image-4.png",
  undone: "/assets/roadmap/undone.svg",
  notification1: "/assets/notification/image-1.png",
  notification2: "/assets/notification/image-2.png",
  notification3: "/assets/notification/image-3.png",
  notification4: "/assets/notification/image-4.png",
  benefitCard1: "/assets/benefits/card-1.svg",
  benefitCard2: "/assets/benefits/card-2.svg",
  benefitCard3: "/assets/benefits/card-3.svg",
  benefitCard4: "/assets/benefits/card-4.svg",
  benefitCard5: "/assets/benefits/card-5.svg",
  benefitCard6: "/assets/benefits/card-6.svg",
  benefitIcon1: "/assets/benefits/icon-1.svg",
  benefitIcon2: "/assets/benefits/icon-2.svg",
  benefitIcon3: "/assets/benefits/icon-3.svg",
  benefitIcon4: "/assets/benefits/icon-4.svg",
  benefitImage2: "/assets/benefits/image-2.png",
  discordBlack: "/assets/socials/discord.svg",
  facebook: "/assets/socials/facebook.svg",
  instagram: "/assets/socials/instagram.svg",
  telegram: "/assets/socials/telegram.svg",
  twitter: "/assets/socials/twitter.svg",
  mailIcon: "/assets/mailIcon.png",
  googleAnalytics: "/assets/google_analytics_icon.png",
  wordpress: "/assets/wordpress.png",
  content: "/assets/content.png",
};

const {
  mailIcon,
  content,
  yourlogo,
  wordpress,
  googleAnalytics,
  googleAds,
  homeSmile,
  socialMediaIcon,
  file02,
  searchMd,
  plusSquare,
  recording03,
  recording01,
  disc02,
  chromecast,
  sliders04,
  discord,
  figma,
  seo,
  framer,
  notion,
  photoshop,
  protopie,
  raindrop,
  slack,
  roadmap1,
  roadmap2,
  roadmap3,
  roadmap4,
  notification2,
  notification3,
  notification4,
  benefitIcon1,
  benefitIcon2,
  benefitIcon3,
  benefitIcon4,
  benefitImage2,
  discordBlack,
  facebook,
  instagram,
  telegram,
  twitter,
} = images;

export const navigation = [
  {
    id: "0",
    title: "Features",
    url: "#features",
  },
  {
    id: "1",
    title: "Pricing",
    url: "#pricing",
  },
  {
    id: "2",
    title: "How to use",
    url: "#how-to-use",
  },
  {
    id: "3",
    title: "Roadmap",
    url: "#roadmap",
  },
  {
    id: "4",
    title: "New account",
    url: "#signup",
    onlyMobile: true,
  },
  {
    id: "5",
    title: "Sign in",
    url: "#login",
    onlyMobile: true,
  },
];

export const heroIcons = [homeSmile, file02, searchMd, plusSquare];

export const notificationImages = [notification4, notification3, notification2];

export const companyLogos = [
  "/assets/brands/Image8.png",
  "/assets/brands/Image2.png",
  "/assets/brands/Image3.png",
  "/assets/brands/Image5.jpg",
  "/assets/brands/Image6.png",
];

export const brainwaveServices = ["Marketing", "Branding", "Web Development", "Web Development"];

export const brainwaveServicesIcons = [recording03, recording01, disc02, chromecast, sliders04];

export const roadmap = [
  {
    id: "0",
    title: "Création & Développement Web",
    text: "Sites institutionnels (Vitrine, corporate, portfolio), E-commerce (Boutique en ligne, marketplaces), Sites de contenu (Blogs, magazines, actualités), Sites éducatifs (Plateformes d'apprentissage, ressources pédagogiques), Services en ligne (Réservation en ligne, applications web), Sites personnels (Blogs et sites personnels).",
    date: "May 2023",
    status: "done",
    imageUrl: roadmap1,
    colorful: true,
  },
  {
    id: "1",
    title: "Design & Branding",
    text: "Création d'identité visuelle, Conception de logos, Supports de communication (Flyers, brochures, cartes de visite).",
    date: "May 2023",
    status: "progress",
    imageUrl: roadmap2,
  },
  {
    id: "2",
    title: "Stratégie Marketing (SEM)",
    text: "SEO (Optimisation pour les moteurs de recherche), SEA (Publicité sur les moteurs de recherche) : Google Ads.",
    date: "May 2023",
    status: "done",
    imageUrl: roadmap3,
  },
  {
    id: "3",
    title: "Communication & Réseaux Sociaux",
    text: "Community Management, Création et planification de contenu (Posts, vidéos, infographies), Publicité sponsorisée (Campagnes META ADS : Facebook, Instagram).",
    date: "May 2023",
    status: "progress",
    imageUrl: roadmap4,
  },
];

export const collabText =
  "With smart automation and top-notch security, it's the perfect solution for teams looking to work smarter.";

export const collabContent = [
  {
    id: "0",
    title: "Seamless Integration",
    text: collabText,
  },
  {
    id: "1",
    title: "Smart Automation",
  },
  {
    id: "2",
    title: "Top-notch Security",
  },
];

export const collabApps = [
  {
    id: "0",
    title: "Google Ads",
    icon: googleAds,
    width: 26,
    height: 36,
  },
  {
    id: "1",
    title: "seo",
    icon: seo,
    width: 34,
    height: 36,
  },
  {
    id: "2",
    title: "Social Media Icon",
    icon: socialMediaIcon,
    width: 36,
    height: 28,
  },
  {
    id: "3",
    title: "MailIcon",
    icon: mailIcon,
    width: 34,
    height: 35,
  },
  {
    id: "4",
    title: "googleAnalytics",
    icon: googleAnalytics,
    width: 34,
    height: 34,
  },
  {
    id: "5",
    title: "wordpress",
    icon: wordpress,
    width: 34,
    height: 34,
  },
  {
    id: "6",
    title: "Content",
    icon: content,
    width: 26,
    height: 34,
  },
  {
    id: "6",
    title: "Content",
    icon: content,
    width: 26,
    height: 34,
  },
];

export const pricing = [
  {
    id: "0",
    title: "Basic",
    description: "AI chatbot, personalized recommendations",
    price: "0",
    features: [
      "An AI chatbot that can understand your queries",
      "Personalized recommendations based on your preferences",
      "Ability to explore the app and its features without any cost",
    ],
  },
  {
    id: "1",
    title: "Premium",
    description: "Advanced AI chatbot, priority support, analytics dashboard",
    price: "9.99",
    features: [
      "An advanced AI chatbot that can understand complex queries",
      "An analytics dashboard to track your conversations",
      "Priority support to solve issues quickly",
    ],
  },
  {
    id: "2",
    title: "Enterprise",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    features: [
      "An AI chatbot that can understand your queries",
      "Personalized recommendations based on your preferences",
      "Ability to explore the app and its features without any cost",
    ],
  },
];

export const benefits = [
  {
    id: "0",
    title: "Création & Développement Web",
    text: "Sites institutionnels (Vitrine, corporate, portfolio), E-commerce (Boutique en ligne, marketplaces), Sites de contenu (Blogs, magazines, actualités), Sites éducatifs (Plateformes d'apprentissage, ressources pédagogiques), Services en ligne (Réservation en ligne, applications web), Sites personnels (Blogs et sites personnels).",
    backgroundUrl: "assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: benefitImage2,
  },
  {
    id: "1",
    title: "Design & Branding",
    text: "Création d'identité visuelle, Conception de logos, Supports de communication (Flyers, brochures, cartes de visite).",
    backgroundUrl: "assets/benefits/card-2.svg",
    iconUrl: benefitIcon2,
    imageUrl: benefitImage2,
    light: true,
  },
  {
    id: "2",
    title: "Stratégie Marketing (SEM)",
    text: "SEO (Optimisation pour les moteurs de recherche), SEA (Publicité sur les moteurs de recherche) : Google Ads.",
    backgroundUrl: "assets/benefits/card-3.svg",
    iconUrl: benefitIcon3,
    imageUrl: benefitImage2,
  },
  {
    id: "3",
    title: "Communication & Réseaux Sociaux",
    text: "Community Management, Création et planification de contenu (Posts, vidéos, infographies), Publicité sponsorisée (Campagnes META ADS : Facebook, Instagram).",
    backgroundUrl: "assets/benefits/card-4.svg",
    iconUrl: benefitIcon4,
    imageUrl: benefitImage2,
    light: true,
  },
  {
    id: "4",
    title: "Marketing Digital",
    text: "Élaboration de stratégies digitales sur-mesure, Emailing & Automatisation (Campagnes ciblées et automatisées), Publicité en ligne (Display, retargeting, etc.).",
    backgroundUrl: "assets/benefits/card-5.svg",
    iconUrl: benefitIcon1,
    imageUrl: benefitImage2,
  },
  {
    id: "5",
    title: "Événementiel & Gestion d'Événements",
    text: "Lancements de produits, Séminaires et conférences, Team-building et événements d'entreprise.",
    backgroundUrl: "assets/benefits/card-6.svg",
    iconUrl: benefitIcon2,
    imageUrl: benefitImage2,
  },
  {
    id: "6",
    title: "Développement d'Applications & Solutions",
    text: "Applications mobiles (iOS & Android), Solutions web & SaaS (Applications en ligne et solutions personnalisées), Maintenance et support (Suivi et optimisation des applications).",
    backgroundUrl: "assets/benefits/card-1.svg",
    iconUrl: benefitIcon3,
    imageUrl: benefitImage2,
  },
  {
    id: "7",
    title: "Maintenance & Support Web",
    text: "Sécurisation et mises à jour, Hébergement & support technique, Audit & optimisation des performances.",
    backgroundUrl: "assets/benefits/card-3.svg",
    iconUrl: benefitIcon4,
    imageUrl: benefitImage2,
  },
];

export const socials = [
  {
    id: "0",
    title: "Discord",
    iconUrl: discordBlack,
    url: "#",
  },
  {
    id: "1",
    title: "Twitter",
    iconUrl: twitter,
    url: "#",
  },
  {
    id: "2",
    title: "Instagram",
    iconUrl: instagram,
    url: "#",
  },
  {
    id: "3",
    title: "Telegram",
    iconUrl: telegram,
    url: "#",
  },
  {
    id: "4",
    title: "Facebook",
    iconUrl: facebook,
    url: "#",
  },
];
