export const images = {
  yourlogo: "/assets/yourlogo.svg",
  brainwave: "/assets/brainwave.svg",
  check: "/assets/check.svg",
  socialMediaIcon: "/assets/Social_media_icon.png",
  check2: "/assets/check-02.svg",
  loading1: "/assets/loading-01.svg",
  seo: "/assets/seo.png",
  brainwaveSymbol: "/assets/brainwave-symbol.svg",
  brainwaveWhiteSymbol: "/assets/brainwave-symbol-white.svg",
  play: "/assets/play.svg",
  googleAds: "/assets/google-ads.png",
  gradient: "/assets/gradient.png",
  smallSphere: "/assets/4-small.png",
  grid: "/assets/grid.png",
  homeSmile: "/assets/home-smile.svg",
  file02: "/assets/file-02.svg",
  searchMd: "/assets/search-md.svg",
  plusSquare: "/assets/plus-square.svg",
  recording03: "/assets/recording-03.svg",
  recording01: "/assets/recording-01.svg",
  disc02: "/assets/disc-02.svg",
  chromecast: "/assets/chrome-cast.svg",
  sliders04: "/assets/sliders-04.svg",
  loading: "/assets/loading.png",
  background: "/assets/background.jpg",
  curve: "/assets/hero/curve.png",
  robot: "/assets/hero/robot.jpg",
  heroVideo: "/assets/hero/Agency.mp4",
  heroBackground: "/assets/hero/hero-background.jpg",
  curve1: "/assets/collaboration/curve-1.svg",
  curve2: "/assets/collaboration/curve-2.svg",
  discord: "/assets/collaboration/discord.png",
  figma: "/assets/collaboration/figma.png",
  framer: "/assets/collaboration/framer.png",
  notion: "/assets/collaboration/notion.png",
  photoshop: "/assets/collaboration/photoshop.png",
  protopie: "/assets/collaboration/protopie.png",
  raindrop: "/assets/collaboration/raindrop.png",
  slack: "/assets/collaboration/slack.png",
  service1: "/assets/services/service-1.png",
  service2: "/assets/services/service-2.png",
  service3: "/assets/services/service-3.png",
  lines: "/assets/pricing/lines.svg",
  stars: "/assets/pricing/stars.svg",
  coins: "/assets/roadmap/coins.png",
  done: "/assets/roadmap/done.svg",
  hero: "/assets/roadmap/hero.png",
  roadmap1: "/assets/roadmap/image-5.jpg",
  roadmap2: "/assets/roadmap/image-6.jpg",
  roadmap3: "/assets/roadmap/image-7.jpg",
  roadmap4: "/assets/roadmap/image-8.jpg",
  undone: "/assets/roadmap/undone.svg",
  notification1: "/assets/notification/image-1.png",
  notification2: "/assets/notification/image-2.png",
  notification3: "/assets/notification/image-3.png",
  notification4: "/assets/notification/image-4.png",
  benefitCard1: "/assets/benefits/card-1.svg",
  benefitCard2: "/assets/benefits/card-2.svg",
  benefitCard3: "/assets/benefits/card-3.svg",
  benefitCard4: "/assets/benefits/card-4.svg",
  benefitCard5: "/assets/benefits/card-5.svg",
  benefitCard6: "/assets/benefits/card-6.svg",
  benefitIcon1: "/assets/benefits/icon-1.svg",
  benefitIcon2: "/assets/benefits/icon-2.svg",
  benefitIcon3: "/assets/benefits/icon-3.svg",
  benefitIcon4: "/assets/benefits/icon-4.svg",
  benefitImage2: "/assets/benefits/image-2.png",
  discordBlack: "/assets/socials/discord.svg",
  facebook: "/assets/socials/facebook.svg",
  instagram: "/assets/socials/instagram.svg",
  telegram: "/assets/socials/telegram.svg",
  twitter: "/assets/socials/twitter.svg",
  mailIcon: "/assets/mailIcon.png",
  googleAnalytics: "/assets/google_analytics_icon.png",
  wordpress: "/assets/wordpress.png",
  content: "/assets/content.png",
};

const {
  mailIcon,
  content,
  yourlogo,
  wordpress,
  googleAnalytics,
  googleAds,
  homeSmile,
  socialMediaIcon,
  file02,
  searchMd,
  plusSquare,
  recording03,
  recording01,
  disc02,
  chromecast,
  sliders04,
  discord,
  figma,
  seo,
  framer,
  notion,
  photoshop,
  protopie,
  raindrop,
  slack,
  roadmap1,
  roadmap2,
  roadmap3,
  roadmap4,
  notification2,
  notification3,
  notification4,
  benefitIcon1,
  benefitIcon2,
  benefitIcon3,
  benefitIcon4,
  benefitImage2,
  discordBlack,
  facebook,
  instagram,
  telegram,
  twitter,
} = images;

export const navigation = [
  {
    id: "0",
    title: "Services",
    url: "#features",
  },
  {
    id: "2",
    title: "About Us",
    url: "#collaboration",
  },
  {
    id: "3",
    title: "Contact Us",
    url: "#contact-us",
  },
  {
    id: "4",
    title: "Mail Us",
    url: "mailto:thenexaim@gmail.com",
    onlyMobile: true,
  },
  {
    id: "5",
    title: "WhatsApp Us",
    url: "https://wa.me/+923432469633",
    onlyMobile: true,
  },
];

export const heroIcons = [homeSmile, file02, searchMd, plusSquare];

export const notificationImages = [notification4, notification3, notification2];

export const companyLogos = [
  "/assets/brands/Image8.png",
  "/assets/brands/Image2.png",
  "/assets/brands/Image3.png",
  "/assets/brands/Image5.jpg",
  "/assets/brands/Image6.png",
];

export const brainwaveServices = [
  "At Nexaim, we specialize in creating impactful digital experiences that help businesses thrive in the online world. With expertise in content management, graphic design, social media strategy, web development, video editing, product shoots, event management, and podcast production, we provide end-to-end solutions tailored to your brand’s needs. Our team believes in innovation, collaboration, and precision, ensuring every project stands out with creativity and excellence. Whether it's managing your social media, designing stunning visuals, or crafting engaging content, Nexaim is your trusted partner in digital growth. Let’s bring your vision to life and build a powerful online presence together!",
];

export const brainwaveServicesIcons = [recording03, recording01, disc02, chromecast, sliders04];

export const roadmap = [
  {
    id: "0",
    title: "Création & Développement Web",
    text: "Sites institutionnels (Vitrine, corporate, portfolio), E-commerce (Boutique en ligne, marketplaces), Sites de contenu (Blogs, magazines, actualités), Sites éducatifs (Plateformes d'apprentissage, ressources pédagogiques), Services en ligne (Réservation en ligne, applications web), Sites personnels (Blogs et sites personnels).",
    date: "May 2023",
    status: "done",
    imageUrl: roadmap1,
    colorful: true,
  },
  {
    id: "1",
    title: "Design & Branding",
    text: "Création d'identité visuelle, Conception de logos, Supports de communication (Flyers, brochures, cartes de visite).",
    date: "May 2023",
    status: "progress",
    imageUrl: roadmap2,
  },
  {
    id: "2",
    title: "Stratégie Marketing (SEM)",
    text: "SEO (Optimisation pour les moteurs de recherche), SEA (Publicité sur les moteurs de recherche) : Google Ads.",
    date: "May 2023",
    status: "done",
    imageUrl: roadmap3,
  },
  {
    id: "3",
    title: "Communication & Réseaux Sociaux",
    text: "Community Management, Création et planification de contenu (Posts, vidéos, infographies), Publicité sponsorisée (Campagnes META ADS : Facebook, Instagram).",
    date: "May 2023",
    status: "progress",
    imageUrl: roadmap4,
  },
];

export const collabText =
  "Avec une Automatisation Intelligente et une Sécurité de Pointe : Travaillez plus malin, plus adapté! Libérez votre potentiel en simplifiant vos opérations comme jamais auparavant.";

export const collabContent = [
  {
    id: "0",
    title: "Intégration transparente",
    text: "Connectez tous vos outils en un clin d’œil, sans effort.",
  },
  {
    id: "1",
    title: "Automatisation Intelligent",
    text: "Laissez l’IA gérer les tâches répétitives pour que vous puissiez vous concentrer sur la créativité. 🧠",
  },
  {
    id: "2",
    title: "Sécurité de Niveau Supérieur",
    text: "Protégez vos données avec un décryptage ultra-sécurisée.",
  },
];

export const collabApps = [
  {
    id: "0",
    title: "Google Ads",
    icon: googleAds,
    width: 26,
    height: 36,
  },
  {
    id: "1",
    title: "seo",
    icon: seo,
    width: 34,
    height: 36,
  },
  {
    id: "2",
    title: "Social Media Icon",
    icon: socialMediaIcon,
    width: 36,
    height: 28,
  },
  {
    id: "3",
    title: "MailIcon",
    icon: mailIcon,
    width: 34,
    height: 35,
  },
  {
    id: "4",
    title: "googleAnalytics",
    icon: googleAnalytics,
    width: 34,
    height: 34,
  },
  {
    id: "5",
    title: "wordpress",
    icon: wordpress,
    width: 34,
    height: 34,
  },
  {
    id: "6",
    title: "Content",
    icon: content,
    width: 26,
    height: 34,
  },
  {
    id: "6",
    title: "Content",
    icon: content,
    width: 26,
    height: 34,
  },
];

export const pricing = [
  {
    id: "0",
    title: "Basic",
    description: "AI chatbot, personalized recommendations",
    price: "0",
    features: [
      "An AI chatbot that can understand your queries",
      "Personalized recommendations based on your preferences",
      "Ability to explore the app and its features without any cost",
    ],
  },
  {
    id: "1",
    title: "Premium",
    description: "Advanced AI chatbot, priority support, analytics dashboard",
    price: "9.99",
    features: [
      "An advanced AI chatbot that can understand complex queries",
      "An analytics dashboard to track your conversations",
      "Priority support to solve issues quickly",
    ],
  },
  {
    id: "2",
    title: "Enterprise",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    features: [
      "An AI chatbot that can understand your queries",
      "Personalized recommendations based on your preferences",
      "Ability to explore the app and its features without any cost",
    ],
  },
];

export const benefits = [
  {
    id: "0",
    title: "Facebook Management",
    text: "Boost your brand’s presence with expert Facebook management by Nexaim! We handle content creation, audience engagement, and ad campaigns to maximize reach and drive results. Let’s grow your business together",
    backgroundUrl: "assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: benefitImage2,
  },
  {
    id: "1",
    title: "Instagram Management",
    text: "Grow your presence with Nexaim’s strategic Instagram management. From stunning visuals to Reels, Stories, and targeted ads, we help you connect with your audience and increase engagement.",
    backgroundUrl: "assets/benefits/card-2.svg",
    iconUrl: benefitIcon2,
    imageUrl: benefitImage2,
    light: true,
  },
  {
    id: "2",
    title: "Youtube Management",
    text: "Expand your reach with Nexaim’s professional YouTube management. We optimize content, enhance SEO, and drive audience growth to boost visibility, engagement, and monetization.",
    backgroundUrl: "assets/benefits/card-3.svg",
    iconUrl: benefitIcon3,
    imageUrl: benefitImage2,
  },
  {
    id: "3",
    title: "Graphic Design & Branding  ",
    text: "Nexaim delivers stunning and impactful designs that elevate your brand. From logos to marketing materials, we create visually compelling graphics that capture attention and leave a lasting impression.",
    backgroundUrl: "assets/benefits/card-4.svg",
    iconUrl: benefitIcon4,
    imageUrl: benefitImage2,
    light: true,
  },
  {
    id: "4",
    title: "Video Editing ",
    text: "Transform your raw footage into high-quality, engaging content with Nexaim’s expert video editing. We enhance visuals, add effects, and ensure a seamless flow to create professional videos that captivate your audience.",
    backgroundUrl: "assets/benefits/card-5.svg",
    iconUrl: benefitIcon1,
    imageUrl: benefitImage2,
  },
  {
    id: "5",
    title: "Product shoot",
    text: "Showcase your products with high-quality, professional photography by Nexaim. We capture stunning visuals that highlight every detail, making your products stand out and drive more sales.",
    backgroundUrl: "assets/benefits/card-6.svg",
    iconUrl: benefitIcon2,
    imageUrl: benefitImage2,
  },
  {
    id: "6",
    title: "Web Development ",
    text: "Nexaim builds fast, responsive, and user-friendly websites tailored to your brand. From design to functionality, we create stunning, high-performing sites that enhance your online presence and drive growth",
    backgroundUrl: "assets/benefits/card-1.svg",
    iconUrl: benefitIcon3,
    imageUrl: benefitImage2,
  },
  {
    id: "7",
    title: "Event Management & Podcast",
    text: "Nexaim delivers seamless event planning and expert podcast management to elevate your brand. From organizing and promoting events to producing high-quality podcasts, we handle everything to engage your audience and create impactful experiences.",
    backgroundUrl: "assets/benefits/card-3.svg",
    iconUrl: benefitIcon4,
    imageUrl: benefitImage2,
  },
];

export const socials = [
  {
    id: "0",
    title: "Discord",
    iconUrl: discordBlack,
    url: "#",
  },
  {
    id: "1",
    title: "Twitter",
    iconUrl: twitter,
    url: "#",
  },
  {
    id: "2",
    title: "Instagram",
    iconUrl: instagram,
    url: "#",
  },
  {
    id: "3",
    title: "Telegram",
    iconUrl: telegram,
    url: "#",
  },
  {
    id: "4",
    title: "Facebook",
    iconUrl: facebook,
    url: "#",
  },
];
